import {Accordion, AccordionItem} from "@nextui-org/react";

export default function FAQ() {

return (
<section className="text-center max-w-[1400px]">
    <p className="text-white text-4xl font-bold mb-10">FAQ</p>
        <div className="text-left">
          <Accordion variant="splitted" selectionMode="multiple">
            <AccordionItem key="1" aria-label="What is UP DeFi?" title="What is UP DeFi?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>UP DeFi is a decentralized finance ecosystem that aims to bridge the gap between various industries and communities by harnessing the potential of blockchain technology. 
              It offers a range of unique tokens tailored to specific industries and social causes, creating opportunities for creators, investors, and charitable initiatives.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="2" aria-label="Accordion 2" title="How does UP DeFi Work" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>UP DeFi operates through a series of tokens, each serving a different purpose and community. These tokens generate dividends from trading tax revenue, which are distributed to investors. 
              The community has a say in project direction, tax rates, and the featured creator, promoting engagement and collaboration.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="3" aria-label="Accordion 3" title="What is Vidiac (VIDI)?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>Vidiac (VIDI) is the inaugural token in the UP DeFi ecosystem. It empowers video content creators to monetize their work by earning rewards from trading tax revenue. 
              Creators compete for the featured wallet spot, determined by the community, and receive support from the ecosystem.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="4" aria-label="Accordion 4" title="How can I join the UP DeFi community?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>Joining the UP DeFi community is simple. You don't need to create an account or provide personal information. 
              Just engage with us on our social media platforms, including Telegram, Discord, Instagram, and X. Participate in discussions and explore the tokens.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="5" aria-label="Accordion 5" title="What are the tax rates within the UP DeFi ecosystem?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>The initial tax rates for buy and sell transactions are set at 20% for the first day of trading and then will drop to 10%.
                  The tax rate is determined by the community and can be changed through a governance vote. 
                Of this tax, 90% goes towards dividends for investors, while 10% directly benefits the featured creator. 
                The total tax rate cannot exceed 20%, ensuring a balanced financial structure.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="6" aria-label="Accordion 6" title="How are taxes collected and distributed?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>Taxes collected within the UP DeFi ecosystem are converted into the stablecoin USDC and distributed as dividends to investors. 
                This mechanism guarantees consistent returns for investors, regardless of token price fluctuations.</p>
             </div>
            </AccordionItem>
            <AccordionItem key="7" aria-label="Accordion 7" title="What security measures are in place?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>The security of UP DeFi's contracts is ensured by the blockchain itself. All contracts are open-source and available for public scrutiny. 
                100,000 team tokens are allocated at launch but will not be sold. The dividends generated by the team tokens will be used to cover salary costs. 
                Liquidity lock duration will initially be 6 months and planned to be re-locked every 6 months. 
                Access to liquidity will only be necessary in the event that the contract no longer functions as planned and a re-launch of the token is required.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="8" aria-label="Accordion 8" title="How can I get involved in UP DeFi's marketing efforts?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>UP DeFi welcomes community members to contribute to marketing efforts. 
                  You can design branding materials, such as stickers, logos, and GIFs, which may be used on UP DeFi's social platforms and merchandise.
                Additionally, consider sharing your positive experiences with UP DeFi to attract more creators and investors.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="9" aria-label="Accordion 9" title="When will the other tokens in the UP DeFi ecosystem be launched?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>The launch of additional tokens in the UP DeFi ecosystem will depend on the success of Vidiac (VIDI) and community feedback. 
                Each token will have its launch, and the timing will be influenced by the community's readiness.</p>
              </div>
            </AccordionItem>
            <AccordionItem key="10" aria-label="Accordion 10" title="How can I contact UP DeFi for inquires or collaborations?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>You can reach out to UP DeFi and explore collaboration opportunities through our official social media platforms, including Telegram and Discord.  Email us at contact@up-defi.com</p>
              </div>
            </AccordionItem>
            <AccordionItem key="11" aria-label="Accordion 11" title="How do I purchase cryptocurrency?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>There are multiple ways to purchase cryptocurrency. Youtube and Google are great assets as they contain many different guides. 
                  This FAQ will sum up the process, but you are encouraged to do further research into best practices.
                  </p>
                <p>Coinbase and Crypto.com are centralized exchanges that allow you to connect a bank account making purchasing cryptocurrency easy and fast. 
                  Cryptocurrency purchased can then be sent to an individual's wallet for use on decentralized exchanges. 
                  Please support UP-Defi by using our referral code here https://crypto.com/app/3ntgxp2axe to sign up for a Crypto.com account and we both get $25 USD.
                  </p>
                <p>When sending cryptocurrency, be sure to send the cryptocurrency to the appropriate network and to an address that can accept it. There are many networks and it is easy to make a mistake. 
                It is best to first send a very small amount as a test so that any losses due to mistakes will be minimal.
                  </p>
                <p>The most common individual non-custodial wallet is MetaMask. This is an app that can be found in the Google Play Store and Apple App Store.
                  It can also be added to web browsers such as Chrome for desktop access. Many wallets now offer the ability to purchase cryptocurrency directly from the app using a debit card or even PayPal. 
                  Often this will be easier than purchasing elsewhere and transferring but will have increased fees associated with the convenience. 
                  Shop around and try various methods to determine which is right for you.
                  </p>
                <p>Below are some helpful videos to get you started.</p>
                <p>How to set up a Crypto.com account:
                https://www.youtube.com/watch?v=haGcIPzePVs</p>
                <p>How to set up a Coinbase account:
                https://www.youtube.com/watch?v=txPx72FSrj4</p>
                <p>How to set up a MetaMask wallet:
                https://www.youtube.com/watch?v=-HTubEJ61zU</p>
              </div>
            </AccordionItem>
            <AccordionItem key="12" aria-label="Accordion 12" title="How do I purchase tokens within the UP DeFi ecosystem?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>Tokens within the UP DeFi ecosystem will be traded on decentralized exchanges and held in an investor's non-custodial wallet.
                See the above FAQ on purchasing cryptocurrency and creating a non-custodial wallet. 
                Once you understand and have completed those steps, the next step is to connect the wallet to the decentralized exchange (DEX) that the token is traded on.
                </p>
                <p>In the case of Vidiac, Uniswap and PancakeSwap will be the DEXs utilized.</p>
                <p>Sign in to your wallet containing ETH token on the Ethereum ERC20 network and navigate to https://app.uniswap.org/ or https://pancakeswap.finance/swap</p>
                <p>Connect your wallet to the site.</p> 
                <p>Select ETH as the token to sell.</p> 
                <p>Paste the contract address for Vidiac into the token to buy section.</p> 
                <p>Click the settings cog and set the slippage based on the token tax rate.</p> 
                <p>Complete the purchase by approving the transaction.</p> 
                <p>Import the Vidiac contract address into your wallet and you will now see the Vidiac tokens.</p>
                <p>
                Uniswap Tutorial:
                https://www.youtube.com/watch?v=nvj2DHEkWfc
                </p>
                <p>PancakeSwap Tutorial:
                https://www.youtube.com/watch?v=r7v2BG3rEXk
                </p>
              </div>
            </AccordionItem>
            <AccordionItem key="13" aria-label="Accordion 13" title="What is blockchain technology?" className="bg-gradient-to-b from-gray-50 to-gray-500">
              <div className="text-lg font-semibold text-white bg-gradient-to-b from-gray-500 to-gray-900 rounded-lg p-4">
                <p>Imagine a blockchain as a digital ledger, similar to a notebook, where you can write down transactions or exchanges of information. 
                  But instead of being in one place, this ledger is duplicated across a network of computers. 
                  This makes it very hard to tamper with, as you would need to change the ledger on every single computer at the same time.
                </p>
                <p>Each 'block' in the blockchain is like a page in this notebook. It contains a bunch of transactions or information. 
                  Once a block is filled with this data, it is sealed and linked to the previous block, forming a chain of blocks – hence the name 'blockchain'.</p>
                <p>These blocks are created through a process called 'mining', which involves computers solving complex mathematical problems. 
                  When they solve these problems, they get the chance to add a new block to the chain.</p>
                <p>One key feature of blockchain is that it's transparent and decentralized. 
                  This means that anyone on the network can view the transactions in the blocks, but no single person or organization has control over the entire chain. 
                  This makes it a very secure and open way of handling data.</p> 
                <p>Blockchain is famously used for cryptocurrencies like Bitcoin, where it records all the transactions securely and transparently. 
                  However, its use is expanding to other areas like contracts, voting systems, and more, due to its secure and transparent nature.</p> 
              </div>
            </AccordionItem>
          </Accordion>
        </div>
    </section>
);
}